INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_1");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_2");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_3");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_4");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_5");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_6");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_7");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_8");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_9");
INSERT INTO jugadores (nombre_jugador) VALUES ("PLAYER_10");
//CATEGORIAS
INSERT INTO CATEGORIAS(NIVEL_CATEGORIA, NOMBRE_CATEGORIA) VALUES(1 ,"GEOGRAFIA");
INSERT INTO CATEGORIAS(NIVEL_CATEGORIA, NOMBRE_CATEGORIA) VALUES(2 ,"FUTBOL");
INSERT INTO CATEGORIAS(NIVEL_CATEGORIA, NOMBRE_CATEGORIA) VALUES(3 ,"QUIMICA");
INSERT INTO CATEGORIAS(NIVEL_CATEGORIA, NOMBRE_CATEGORIA) VALUES(4 ,"SOCIALES");
INSERT INTO CATEGORIAS(NIVEL_CATEGORIA, NOMBRE_CATEGORIA) VALUES(5 ,"HISOTIRA");

//DIFICULTAD
INSERT INTO DIFICULTADES(NIVEL_DIFICULTAD, NOMBRE_DIFICULTAD) VALUES(1 ,"MUY FACIL");
INSERT INTO DIFICULTADES(NIVEL_DIFICULTAD, NOMBRE_DIFICULTAD) VALUES(2 ,"FACIL");
INSERT INTO DIFICULTADES(NIVEL_DIFICULTAD, NOMBRE_DIFICULTAD) VALUES(3 ,"MEDIO");
INSERT INTO DIFICULTADES(NIVEL_DIFICULTAD, NOMBRE_DIFICULTAD) VALUES(4 ,"DIFICIL");
INSERT INTO DIFICULTADES(NIVEL_DIFICULTAD, NOMBRE_DIFICULTAD) VALUES(5 ,"MUY DIFICIL");

//RONDAS
INSERT INTO RONDAS(DESCRIPCION_RONDA, NUMERO_RONDA) VALUES("PRIMERA RONDA", 1);
INSERT INTO RONDAS(DESCRIPCION_RONDA, NUMERO_RONDA) VALUES("SEGUNDA RONDA", 2);
INSERT INTO RONDAS(DESCRIPCION_RONDA, NUMERO_RONDA) VALUES("TERCERA RONDA", 3);
INSERT INTO RONDAS(DESCRIPCION_RONDA, NUMERO_RONDA) VALUES("CUARTA RONDA", 4);
INSERT INTO RONDAS(DESCRIPCION_RONDA, NUMERO_RONDA) VALUES("RONDA FINAL", 5);

//PREMIOS
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(10);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(20);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(30);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(40);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(50);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(60);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(70);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(80);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(90);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(100);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(110);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(120);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(130);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(140);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(150);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(160);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(170);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(180);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(190);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(200);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(210);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(220);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(230);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(240);
INSERT INTO PREMIOS(DESCRIPCION_PREMIO) VALUES(250);

//PREGUNTAS
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cual es la capital de Amazonas?",1,1,1,1,1 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Pais ganador del mundial de futbol 1990?",2,2,2,2,1 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿El elemento ZR hace referencia en la tabla periodica a?",3,3,3,3,1 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cual es la ciudad más poblada de Europa?",4,4,4,4,1 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cual era la capital del imperio Inca?",5,5,5,5,1 );

INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la capital de Antioquia?",6,1,1,6,2 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Pais ganador del mundial de futbol 2006?",7,2,2,7,2 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿El elemento SB hace referencia en la tabla periódica a?",8,3,3,8,2 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la ciudad más poblada de América?",9,4,4,9,2 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cual era el nombre del Dios del Sol en el antiguo Egipto?",10,5,5,10,2 );

INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la capital de Vichada?",11,1,1,11,3 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Pais ganador del mundial de futbol 2010?",12,2,2,12,3 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿El elemento NP hace referencia en la tabla periódica a?",13,3,3,13,3 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la ciudad más poblada de Asia?",14,4,4,14,3 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cómo se llamo el avion mas rapido del mundo que dejo de volar tras un fatidico accidente aereo?",15,5,5,15,3 );

INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la capital de Guainia?",16,1,1,16,4 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Pais ganador del mundial de futbol 1970?",17,2,2,17,4 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿El elemento SC hace referencia en la tabla periódica a?",18,3,3,18,4 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la ciudad más poblada de África?",19,4,4,19,4 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Quién inicio la Revolucion China?",20,5,5,20,4 );

INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la capital de Vaupes?",21,1,1,21,5 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Pais ganador del mundial de futbol 1982?",22,2,2,22,5 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿El elemento HG hace referencia en la tabla periódica a?",23,3,3,23,5 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Cuál es la ciudad más poblada de Oceanía?",24,4,4,24,5 );
INSERT INTO PREGUNTAS(DESCRIPCION_PREGUNTA, NUMERO_PREGUNTA, CATEGORIAS_ID_CATEGORIA, DIFICULTADES_ID_DIFICULTAD, PREMIOS_ID_PREMIO, RONDAS_ID_RONDA) VALUES("¿Qué emperador romano legalizo el cristianimo y puso fin a la perecucion de los cristianos ?",25,5,5,25,5 );

//RESPUESTAS
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MITU",1);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MEDELLIN",1);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"LETICIA",1);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CALI",1);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BRASIL",2);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ALEMANIA",2);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ARGENTINA",2);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ITALIA",2);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"COBALTO",3);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ARSENICO",3);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"SILICIO",3);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"CIRCONIO",3);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ESTAMBUL",4);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"LONDRES",4);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ROMA",4);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PARIS",4);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"QUITO",5);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"LIMA",5);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MACHUPICHU",5);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"CUSCO",5);


INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CALI",6);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"MEDELLIN",6);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BOGOTA",6);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PPOPAYAN",6);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BRASIL",7);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ALEMANIA",7);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ARGENTINA",7);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ITALIA",7);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ANTIMONIO",8);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BARIO",8);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"SILICIO",8);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BISMUTO",8);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"NEW YORK",9);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CIUDAD DE MEXICO",9);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CIUDAD DE PANAMA",9);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"SAN PABLO",9);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"OSIRIS",10);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"RA",10);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"HORUS",10);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"SETH",10);


INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"YOPAL",11);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"PUERTO CARREÑO",11);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PUERTO INIRIDA",11);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"VILLAVICENCIO",11);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ALEMANIA",12);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ESPAÑA",12);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"HOLANDA",12);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"URUGUAY",12);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"NEPTUNIO",13);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"NEOMIDIO",13);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PROTACTINIO",13);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"NEON",13);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BEIJING",14);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"NUEVA DELHI",14);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PEKIN",14);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"TOKIO",14);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ANTONOV",15);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BOEING 747",15);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"CONCORDE",15);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BELL X2",15);


INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PUERTO GAITAN",16);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"PUERTO INIRIDA",16);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MITU",16);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PUERTO GUAINIA",16);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"BRASIL",17);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"INGLATERRA",17);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"UNION SOVIETICA",17);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ITALIA",17);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ESTRONCIO",18);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"SEABORGIO",18);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ESCANDIO",18);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"SAMARIO",18);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"LUANDA",19);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CIUDAD DEL CABO",19);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"EL CAIRO",19);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"LAGOS",19);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"DENG XIAOPING",20);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MAO ZETUNG",20);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"MAO ZEDONG",20);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"QIN SHI HUANG",20);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PUERTO LEGUIZAMO",21);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PUERTO VAUPES",21);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"MITU",21);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"FLORENCIA",21);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ALEMANIA",22);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"BRASIL",22);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"ARGENTINA",22);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"ITALIA",22);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"HAFNIO",23);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"HIDROGENIO",23);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"MERCURIO",23);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"HELIO",23);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"SIDNEY",24);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"MELBOURE",24);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"PERTH",24);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"GOLD COAST",24);

INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"CALIGULA",25);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"NERON",25);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(0,"AUGUSTO",25);
INSERT INTO RESPUESTAS(CORRECTA, DESCRIPCION_RESPUESTA, PREGUNTA_ID_PREGUNTA) VALUES(1,"CONSTANTINO",25);


//CONTROL_JUEGO
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,4500,1,10);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,3000,2,9);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,3500,3,8);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,25000,4,7);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,2000,5,6);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,1800,6,5);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,1500,7,4);
INSERT INTO CONTROL_JUEGO(JUEGO_ACTIVO, PUNTAJE, JUGADORES_ID_JUGADOR, PREGUNTAS_ID_PREGUNTA) VALUES(0,1000,8,3);